### ISSUE TITLE
invalid yaml?

### ISSUE THREAD

**Issue by jcputter** [evryfs/github-actions-runner-operator#169]
Trying to apply the example yaml i get

```The GithubActionRunner "runner-pool" is invalid:
* spec.podTemplateSpec.apiVersion: Required value: must not be empty
* spec.podTemplateSpec.kind: Required value: must not be empty

**Comment by davidkarlsen** [comment]
This was caused by https://github.com/evryfs/github-actions-runner-operator/commit/7d978f3639e49c5dc9a067fb86e668226ee5fc26.

For now you can add:
```yaml
apiVersion: v1
kind: Pod
```

until I figure out if this should be like this or not.

Asked for advice in https://kubernetes.slack.com/archives/CAW0GV7A5/p1611319003018100

**Comment by davidkarlsen** [comment]
Maybe @sabre1041 has advice?

**Comment by davidkarlsen** [comment]
Fixed in latest release. Sorry for the noise.
Be sure to apply the updated CRD to avoid this problem: 
```shell
kubectl replace -f https://github.com/evryfs/github-actions-runner-operator/blob/v0.8.3/config/crd/bases/garo.tietoevry.com_githubactionrunners.yaml
```

**Comment by jcputter** [comment]
thanks, I installed the 0.8.3 via helm still having the same issue?

**Comment by jcputter** [comment]
```kubectl replace -f https://github.com/evryfs/github-actions-runner-operator/blob/v0.8.3/config/crd/bases/garo.tietoevry.com_githubactionrunners.yaml
error: error parsing https://github.com/evryfs/github-actions-runner-operator/blob/v0.8.3/config/crd/bases/garo.tietoevry.com_githubactionrunners.yaml: error converting YAML to JSON: yaml: line 88: mapping values are not allowed in this context

**Comment by davidkarlsen** [comment]
Use the raw url https://raw.githubusercontent.com/evryfs/github-actions-runner-operator/v0.8.3/config/crd/bases/garo.tietoevry.com_githubactionrunners.yaml

**Comment by jcputter** [comment]
Thanks, i'm using a PAT and have my secret set (using GH_TOKEN var). My runners are failing to launch.
 
ouput from a pool runner

``Must define RUNNER_TOKEN variable

Has something else changed?

Thanks for the assistance

**Comment by jcputter** [comment]
got it fixed, thanks

**Comment by brian-pickens** [comment]
@jcputter could you please share your fix?
